name: Content Translation

on:
  push:
    branches: [ main ]
    paths:
      - 'trees/**/*.md'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: "translation-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 修正点：简化Node.js设置
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      - name: Install Python dependencies
        run: pip install -r ./translate/requirements.txt

      - name: Install Kodama CLI
        run: |
          # 优先尝试二进制安装
          wget https://github.com/Lampese/kodama-streaming-release/releases/latest/download/kodama
          chmod +x kodama
          sudo mv kodama /usr/local/bin/
          
          # 验证安装
          kodama --version

      - name: Configure Git
        run: |
          git config --global user.name "Translation Bot"
          git config --global user.email "bot@community-blog"

      - name: Run translation
        env:
          API_KEY: ${{ secrets.TRANSLATION_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python ./translate/github_translator.py \
            --source-dir ./trees \
            --target-dir ./trees_en \
            --pr-reviewers "reviewer1,reviewer2"

      - name: Validate output
        run: |
          if [ ! -d "./trees_en" ]; then
            echo "::error::No translated content generated"
            exit 1
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "[Bot] Translated Content Updates"
          body: |
            Automated translation of Markdown content.
            Changes include:
            - Translated files from ./trees to ./trees_en
            - Preserved Markdown formatting
          branch: "content-translation"
          labels: "translation,bot"
          reviewers: reviewer1,reviewer2